# ===========================================
# SIMPLE COLOR SCHEME
# ===========================================

# Primary Colors (plan:: Xbox 360 Blades Dashboard style or just halo theme ??)
$blade-green = rgb(00ff88)      # green
$terminal-bg = rgba(0a0a12ee)   # grey
$hud-cyan = rgb(00ccff)         # cyan
$warning-red = rgb(ff3300)      # red
$warning-yellow = rgb(ffcc00)   # yellow
$grid-purple = rgb(cc00ff)      # purple

# Secondary Colors
$dark-bg = rgba(0a0a0add)       # 
$light-text = rgb(cccccc)       # 
$medium-gray = rgb(595959)      # 
$grid-blue = rgb(0066ff)        #

# Border Gradients
$gradient-primary = $blade-green $hud-cyan 45deg
$gradient-warning = $warning-red $warning-yellow 45deg
$gradient-secondary = $grid-purple $grid-blue 45deg