# ===========================================
#               UNSC-DRESDEN
#          simple Halo style theme
#      GENERAL SETTINGS & DECORATION
# ===========================================

source = colors.conf
source = animation.conf

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2
    col.active_border = $gradient-primary
    col.inactive_border = rgba(595959aa)

    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 0

    shadow {
        enabled = true
        range = 12
        render_power = 2
        color = $dark-bg
    }

    blur {
        enabled = true
        size = 3
        passes = 1
	noise = 0.02
	contrast = 1
	brightness = 1
	vibrancy = 0.5
        vibrancy_darkness = 0.0
    }
    
    dim_inactive = true
    dim_strength = 0.2
    dim_special = 0.1

}

